### ISSUE TITLE
Update cover letter for pilot 3

### ISSUE THREAD

**Issue by laxamanaj** [RConsortium/submissions-pilot3-adam-to-fda#1]

**Comment by zhaol30** [comment]
@laxamanaj Hi Joel, The current version of the [cover letter](https://github.com/RConsortium/submissions-pilot3-adam-to-fda/blob/main/m1/us/cover-letter.pdf) actually looks good to me. I think it reflects the Pilot 3 deliverables already and you've updated it at the beginning of this project. Please let me know if anything I missed and can help more. Many thanks!

**Comment by laxamanaj** [comment]
Thanks for your review, @zhaol30 .  I will close this issue now since no change/updates are needed.
