### ISSUE TITLE
Copy script to also include defines, specs and renv.lock

### ISSUE THREAD

**Issue by laxamanaj** [RConsortium/submissions-pilot3-adam-to-fda#17]
Hi, @DeclanHodges .

Please let me know if you have bandwidth to do this, but in your copy script here : https://github.com/RConsortium/submissions-pilot3-adam-to-fda/blob/main/m5/datasets/rconsortiumpilot3/batch_copy.sh

Please also include the copy of `define.xml, define2-0-0.xsl and ADaM - Pilot 3.xlsx` from https://github.com/RConsortium/submissions-pilot3-adam/tree/main/submission/adam to https://github.com/RConsortium/submissions-pilot3-adam-to-fda/tree/main/m5/datasets/rconsortiumpilot3/analysis/adam 

Please also copy over the `renv.lock` file from https://github.com/RConsortium/submissions-pilot3-adam/blob/main/renv.lock to here https://github.com/RConsortium/submissions-pilot3-adam-to-fda/tree/main/m5/datasets/rconsortiumpilot3/analysis/programs

Let me know if you have any questions.

**Comment by DeclanHodges** [comment]
Hi @laxamanaj, I'll make the update. 

Did you mean `TDF_ADaM - Pilot 3 Team updated.xlsx` rather than `ADaM - Pilot 3.xlsx` from the `adam` directory?

**Comment by laxamanaj** [comment]
Hi, @DeclanHodges .  I actually changed the name of the .xlsx to be more general and say 'ADaM - Pilot 3.xlsx'.

**Comment by DeclanHodges** [comment]
Note to update repo and ADRG readme's to reflect above changes.

**Comment by DeclanHodges** [comment]
@laxamanaj, could you please confirm where in the ADRG we need to update to reflect the addition of the define, specs and renv.lock files?

**Comment by laxamanaj** [comment]
Thanks @DeclanHodges .  

For ADRG, update Section 8 : https://docs.google.com/document/d/13xMUVQgZMmXd1igdZNUQy1Pc-WxoMxL7/edit?usp=sharing&ouid=103991081896680964420&rtpof=true&sd=true 

and in the README of this repo.

**Comment by DeclanHodges** [comment]
> For ADRG, update Section 8 : https://docs.google.com/document/d/13xMUVQgZMmXd1igdZNUQy1Pc-WxoMxL7/edit?usp=sharing&ouid=103991081896680964420&rtpof=true&sd=true

Thanks for confirming @laxamanaj - the ADRG is updated with the new structure.
