### ISSUE TITLE
Move batch_copy.sh and renv.lock

### ISSUE THREAD

**Issue by laxamanaj** [RConsortium/submissions-pilot3-adam-to-fda#21]
Hi, @DeclanHodges .

Would it be possible to move the batch_copy.sh outside of the m5 directory and have it in the root folder and still be able to run from the root?  When FDA extracts the package, we shouldn't see the copy script in the m5. 
![image](https://github.com/RConsortium/submissions-pilot3-adam-to-fda/assets/95468392/82560dfa-9fc1-4d82-90da-bb9108af8ea3)

**Comment by DeclanHodges** [comment]
Note to also move renv.lock file to submissions-pilot3-adam-to-fda directory.
