### ISSUE TITLE
Update eCTD structure and remove unnecessary files. 

### ISSUE THREAD

**Issue by laxamanaj** [RConsortium/submissions-pilot3-adam-to-fda#23]
- [x] The output folder is not part of eCTD structure.  This needs to be removed.
- [x] Update eCTD structure so that it looks like this : 
![image](https://github.com/RConsortium/submissions-pilot3-adam-to-fda/assets/95468392/4fb6f4f6-bde3-45bf-af31-0ddd02418eb9)

- [x] Update the file structure in README.md 

- [x] Update the file structure in the ADRG https://docs.google.com/document/d/13xMUVQgZMmXd1igdZNUQy1Pc-WxoMxL7/edit?usp=sharing&ouid=103991081896680964420&rtpof=true&sd=true 
- [ ] Update path in ADRG to call on the correct directories.

**Comment by DeclanHodges** [comment]
Hi @laxamanaj,
Where should we have the rtf files if we're removing the output directory?

**Comment by laxamanaj** [comment]
Thanks for checking, @DeclanHodges .  The TLF programs are ok to stay where they are!  Pilot1 also submitted them in this same folder : https://github.com/RConsortium/submissions-pilot1-to-fda/tree/main/m5/datasets/rconsortiumpilot1/analysis/adam/programs

**Comment by laxamanaj** [comment]
> Hi @laxamanaj, Where should we have the rtf files if we're removing the output directory?

Thanks, @DeclanHodges .  We just delete them as we will have them in the report-tlf.pdf file.

**Comment by DeclanHodges** [comment]
Thanks for your responses @laxamanaj. 

Unfortunately, I'm having trouble updating the ADRG path, as the document doesn't seem to be rendering properly when I try to open in Google Docs. Would you be able to make the update for me? From what I can see, it is just this part which needs updating:
![image](https://github.com/RConsortium/submissions-pilot3-adam-to-fda/assets/113363343/cc1d14cb-1ec5-4587-8ef2-f53d0ddd8254)
