### ISSUE TITLE
renv.lock not a file listed in eCTD guidance

### ISSUE THREAD

**Issue by laxamanaj** [RConsortium/submissions-pilot3-adam-to-fda#26]
As we see here the .lock file is not part of the eCTD guidance : https://www.fda.gov/media/85816/ 

But, this is still a text file which could still be ok to submit.  I've sent an email to Paul and HyeSoo to ask if they'd be willing to accept the renv.lock as-is, which may drive an update to this eCTD guidance.

But in the case, the renv.lock is not allowed at this time, can we create a test branch where when the copy script is run, that it actually adds the .txt extension to the renv.lock file, that is copy as renv.lock --> renv.lock.txt?  Then in the ADRG we'll include instruction to change the file name back to just renv.lock.  Then we need to re-test that this would still work.

**Comment by laxamanaj** [comment]
![image](https://github.com/RConsortium/submissions-pilot3-adam-to-fda/assets/95468392/ed8dd5f0-924a-465e-9052-988a54e0bc34)

**Comment by laxamanaj** [comment]
Paul, from the FDA was able to confirm with us. 
![image](https://github.com/RConsortium/submissions-pilot3-adam-to-fda/assets/95468392/f26b0d64-20d7-4616-8964-fa22877717c6)

@DeclanHodges , in the case you have the new branch set-up where it copies the renv.lock file and updates it to renv.txt, feel free to do a pull request.  Then we'll need to update the adrg steps.

If Declan doesn't have bandwidth, if anyone else can work on this, please comment and let us know.

**Comment by DeclanHodges** [comment]
Hi @laxamanaj,
I've updated the copy script (PR linked above). I'm unable to edit the ADRG though, so if someone else could make that change, that would be great!
