### ISSUE TITLE
package name inconsistency in adrg

### ISSUE THREAD

**Issue by fb-elong** [RConsortium/submissions-pilot3-adam-to-fda#35]
If there is a plan to update adrg, please consider below item. 

Section 7.4 

While reading ADRG, it looks like package name `Pilot3` is not being  consistent with the hyper link with a package called "pilot3utils".  https://github.com/RConsortium/submissions-pilot3-utilities/blob/main/DESCRIPTION

Section 7.5 

remove `pilot3` package row as that's not on CRAN.

**Comment by laxamanaj** [comment]
Yes, this was also mentioned in our last meeting in R Consortium Submission WG.  We will need to update this.

**Comment by laxamanaj** [comment]
The adrg is being updated here : https://github.com/RConsortium/submissions-pilot3-adam/pull/162 will continue conversation in linked issue and will close this one.
