### ISSUE TITLE
renv and R version

### ISSUE THREAD

**Issue by fb-elong** [RConsortium/submissions-pilot3-adam-to-fda#36]
renv will complain if people from FDA use a different R version other than the one defined in 

https://github.com/RConsortium/submissions-pilot3-adam-to-fda/blob/main/m5/datasets/rconsortiumpilot3/analysis/adam/programs/renv-lock.txt#L3

**Comment by laxamanaj** [comment]
Thanks for noting this, @fb-elong .  From the last R Consortium Call it seemed that the FDA reviewer that had the correct R version was able to get through the renv:: restore() ok.  I'm hoping the other FDA reviewer is able to get the R version that matches per our steps.

**Comment by laxamanaj** [comment]
This is being further discussed in other forums within the R Consortium - https://rconsortium.github.io/submissions-wg/minutes/2024-03-01/ , but still agree with your initial comment.  So long as sponsor denotes the version to use in the submission (i.e. the adrg), the FDA reviewer should review the sponsor submission using specified version.
