### ISSUE TITLE
Update Pilot3 programs for .zip build+run with pilot3utils namespace and library reference

### ISSUE THREAD

**Issue by robertdevine** [RConsortium/submissions-pilot3-adam-to-fda#40]
With the .zip package installation instructions, the programs need updated reference to the package namespace and library for build and run. See [here](https://github.com/RConsortium/submissions-pilot3-adam/issues/167#issuecomment-1998457428) for details. thx.

**Comment by laxamanaj** [comment]
Hi, @robertdevine 

I just saw this.  Do you suggest we do all of the testing from this branch before we move to main?  I was about to run the copy script in `main` to bring in all of the current programs and documents from the project repo into here.

anyone have a preference?

@bms63 @AlexandraP-21 @kaz462

**Comment by laxamanaj** [comment]
> Hi, @robertdevine
> 
> I just saw this. Do you suggest we do all of the testing from this branch before we move to main? I was about to run the copy script in `main` to bring in all of the current programs and documents from the project repo into here.
> 
> anyone have a preference?
> 
> @bms63 @AlexandraP-21 @kaz462

Just to save time, I went ahead and just copied everything to this branch.  When doing testing and downloading the eCTD pilot 3 submission structure, please make sure to switch to this 40 branch first, then download the .zip.

![image](https://github.com/RConsortium/submissions-pilot3-adam-to-fda/assets/95468392/d13e8783-a2d3-4d3d-8c55-bffa9724ce12)

The adrg.pdf in the m5 should also be the latest and updated. Fixed the layouts and manually fixed the wrapping.  Test away!!!

**Comment by bms63** [comment]
Roger roger!

**Comment by robertdevine** [comment]
Hi @laxamanaj - yes, that branch selection should be appropriate. So far, the testing is going very well. During the testing if you start with the renv-lock.txt from the Installation Instructions issue (closed earlier today) then snapshot to install pilot3utils your test sandbox actually matches what we have been doing here - so, in summary, using the branch you identified here to complete the tests prior to merge onto main should be fine. I have run into no issues -including fast forwarding all code changes into the latest source changes. thx

**Comment by robertdevine** [comment]
@laxamanaj , @bms63 - just to be certain pilot3 team is aware the difference between the .txt lock provided with the Installation Instructions differs from the snapshot due to the {pilot3utils} package (which gets appended to the lock during the installation process. A nuance to be aware of since the actual {pilot3utils} package dependency appears in the proprietary pilot3 lock file. thx.

![image](https://github.com/RConsortium/submissions-pilot3-adam-to-fda/assets/8195239/fb7a6558-7336-4984-9fc8-b6ec7f4a4ad9)

**Comment by bms63** [comment]
I think pilto3utils in renv.lock file could use a refresh - pilto3utils should be Version `0.0.2`

**Comment by robertdevine** [comment]
Thx. @bms63 
![image](https://github.com/RConsortium/submissions-pilot3-adam-to-fda/assets/8195239/f829b094-725b-43e1-8de4-7de31f1d712f)

All programs/outputs run successfully. I'll issue the PR. thx. again.

**Comment by bms63** [comment]
Thanks Robert!!
