### ISSUE TITLE
Restructure our data directories for rconsortiumpiolot3

### ISSUE THREAD

**Issue by laxamanaj** [RConsortium/submissions-pilot3-adam-to-fda#8]
1. rename the directory `rconsortiumpilot1` to `rconsortiumpilot3`
2. Please remove the `adam` directory from here : 
![image](https://github.com/RConsortium/submissions-pilot3-adam-to-fda/assets/95468392/d92bbab1-725f-4827-a62b-13799407bf1a)

3. Then rename the `analysis` directory to `tabulations`.
4. Under the new  `rconsortiumpilot3` directory create `analysis/adams`.
5. Once the last batch run is complete in 'main' from #108 https://github.com/RConsortium/submissions-pilot3-adam/pull/108 we will copy the adams into new directory in step 4.

**Comment by DeclanHodges** [comment]
Hi @laxamanaj, I've restructured the directories (as per steps 1 - 4). Even though they should be the same, shall we also copy over our SDTMs from the dev repo for the sake of traceability as part of step 5?

**Comment by laxamanaj** [comment]
This is a good point.  Yes, please go ahead and do. It shows steps from the development area leading to submission as it were a regular study.
